name: Build & Push Nginx Docker Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Generate HTML via Ansible
        run: ansible-playbook -i ansible/inventory.ini ansible/playbook.yml --extra-vars "github_run_number=${{ github.run_number }}"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: HTML Lint
        run: |
          sudo apt-get update && sudo apt-get install -y tidy
          tidy -qe index.html

      - name: Lint Nginx config
        run: |
          docker run --rm -v $(pwd)/nginx.conf:/etc/nginx/nginx.conf nginx:stable-alpine nginx -t

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:${{ github.run_number }} .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:${{ github.run_number }}

      - name: Update Deployment YAML with new image
        run: |
          sed -i "s|image: ghcr.io/vmykhailyk/mynginx:.*|image: ghcr.io/vmykhailyk/mynginx:${GITHUB_RUN_NUMBER}|g" manifests/deployment.yaml
          git add manifests/deployment.yaml
          git commit -m "Update deployment image to $GITHUB_RUN_NUMBER" || echo "No changes"
          git push





